Adding Fish Storage Struct
MangoLocoStudios/gone-fish pull request #13
Opened 2023-11-10 06:55 UTC by tkapa

#12

Adds `fish_storage.rs` 

Attaches a FishStorage to the player entity.

Allows us to use `FishStorage::update_storage` to update a storage.

2023-11-10 13:09 UTC, SamBWagner requested changes

2023-11-10 13:09 UTC, SamBWagner commented on src/fish_storage.rs
I'm not conviced by fish storage. I think generic storage would be more pog.

2023-11-11 04:54 UTC, SamBWagner commented on src/fish_storage.rs
actually. I don't think it matters for nwo

2023-11-11 04:54 UTC, tkapa commented on src/fish_storage.rs
How so?

Do you mean that we should just rename `FishStorage` to `Storage`?

2023-11-11 04:55 UTC, SamBWagner approved these changes

2023-11-11 04:55 UTC, SamBWagner commented on src/fish_storage.rs
I think the solution architecture could be more in line with having individual store components inside a larger `storage` component/entity
meaning you could compose any type of storage. But it's too much yours is more pog

2023-11-11 05:01 UTC, tkapa commented on src/fish_storage.rs
For now, I think we only care about tracking the capacity of the storage, and the max value of the Storage

I think there's an argument for renaming this to `storage` instead and expanding upon your idea later if applicable.

2023-11-11 05:10 UTC, merged